version: '3'
services:

  express:
    container_name: ${NODE_NAME}
    build: ./
    ports:
      - "${NODE_PORT}:3000"
    volumes:
      - .:/app/node
    links:
      - mysql
      - web
  web:
    container_name: ${WEB_NAME}
    build: ../web
    ports:
      - ${WEB_PORT}:8080
    volumes:
      - ../web:/app/web
  mysql:
    container_name: ${DB_HOST}
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    security_opt:
      - seccomp:unconfined
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASS}
